name: Remove Old Images

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  delete-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permiso necesario para hacer push al repositorio

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Buscar y eliminar imágenes jpg, jpeg y png
        run: |
          find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -delete

      - name: Hacer commit y push de los cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Agregar los archivos eliminados al stage
          git add -u
          
          # Verificar si hay cambios antes de hacer commit
          if git diff-index --quiet HEAD; then
            echo "No se encontraron imágenes para eliminar."
          else
            git commit -m "chore: eliminar imágenes antiguas (jpg, jpeg, png) para migrar a webp"
            git push
          fi
